[theme]
primaryColor = "#1E88E5"
backgroundColor = "#D0D0D0"          # darker gray background
secondaryBackgroundColor = "#F0F0F0" # cards / widgets a bit lighter
textColor = "#222222"
font = "sans serif"
